[package]
authors = ["Philippe Lafontaine <lafontaine.philippe@gmail.com>"]
edition = "2018"
name    = "todo-web"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.2.2"
actix-rt    = "1.1.1"
base64      = "0.12.3"
listenfd    = "0.3"
rustls      = "0.16.0"
serde_json  = "1.0.57"

    [dependencies.actix-web]
    features = ["rustls"]
    version  = "2.0.0"

    [dependencies.async-std]
    features = ["unstable"]
    version  = "1.6.3"

    [dependencies.serde]
    features = ["derive"]
    version  = "1.0.115"

    [dependencies.sqlx]
    default-features = false
    features         = ["macros", "postgres", "chrono", "uuid", "runtime-actix"]
    version          = "0.4.0-beta.1"

    [dependencies.todo-web-shared]
    features = ["actix"]
    path     = "../shared"
