[package]
authors = ["Philippe Lafontaine <lafontaine.philippe@gmail.com>"]
edition = "2018"
name    = "todo-web-shared"
version = "0.1.0"

[dependencies]
serde_json = "1.0.57"

    [dependencies.serde]
    features = ["derive"]
    version  = "1.0.115"
